import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "Fira Code"

[font.bold_italic]
family = "Fira Code"

[font.italic]
family = "Fira Code"

[font.normal]
family = "Fira Code"

[font.offset]
x = 0
y = 7

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"
