#!/bin/sh

export DOTFILES=~/.dotfiles

source $DOTFILES/lib/utils.sh

backup_dir="$DOTFILES/backups/$(date "+%Y_%m_%d-%H_%M_%S")/"

e_line "\nSetting up system. May require root password."

sh $DOTFILES/lib/install.sh

# login npm
npm adduser

# link dotfiles
e_header 'Link dotfiles'
find -H "$DOTFILES/dotfiles" -maxdepth 2 -iname ".*" | while read src; do
  dst="$HOME/$(basename "${src%*}")"
  if [[ -e "$dst" ]]; then
    e_line "Backing up ${dst/#$HOME\//}"

    [[ -e "$backup_dir" ]] || mkdir -p "$backup_dir"
      mv "$dst" "$backup_dir"
  fi
  ln -s "$src" "$dst"
  e_line "Linked ${src/#$HOME/~} to ${dst/#$HOME/~}"
done

if [[ -e $backup_dir ]]; then
  e_line "\nBackups were moved to ${backup_dir/#$HOME/~}"
fi

# enable zsh shell
if [[ "$SHELL" != "/bin/zsh" ]]; then
  chsh -s $(which zsh)
fi

e_header 'Install Oh My Zsh'
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

e_header 'Install ZSH theme'
mkdir -p "$ZSH_CUSTOM/themes/"
cd $DOTFILES
git clone https://github.com/denysdovhan/spaceship-prompt.git
cd spaceship-prompt
ln -s "$PWD/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

## set macOS options
# show invisible files
e_header "Set macOS options and defaults"

e_line "Show invisible files on macOS"
defaults write com.apple.finder AppleShowAllFiles -bool true

# show file extensions
e_line "Show file extensions"
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# expand save dialog
e_line "Expand save dialog"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# enable keyboard for dialogs
e_line "Enable keyboard for dialogs"
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# use current dir as search scope
e_line "Use current directory as search scope"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

killall Finder

# save screenshots in a seperate folder
mkdir ~/Screenshots
defaults write com.apple.screencapture location ~/
killall SystemUIServer

e_success "System is ready to use!"
