#!/bin/sh

export DOTFILES=~/.dotfiles

source $DOTFILES/lib/utils.sh

backup_dir="$DOTFILES/backups/$(date "+%Y_%m_%d-%H_%M_%S")/"

e_line "\nSetting up system. May require root password."

# enable zsh shell
if [[ "$SHELL" != "/bin/zsh" ]]; then
  chsh -s $(which zsh)
fi

# link dotfiles
e_header 'Link dotfiles'
find -H "$DOTFILES/dotfiles" -maxdepth 2 -iname ".*" | while read src; do
  dst="$HOME/$(basename "${src%*}")"
  if [[ -e "$dst" ]]; then
    e_line "Backing up ${dst/#$HOME\//}"

    [[ -e "$backup_dir" ]] || mkdir -p "$backup_dir"
      mv "$dst" "$backup_dir"
  fi
  ln -s "$src" "$dst"
  e_line "Linked ${src/#$HOME/~} to ${dst/#$HOME/~}"
done

if [[ -e $backup_dir ]]; then
  e_line "\nBackups were moved to ${backup_dir/#$HOME/~}"
fi

sh $DOTFILES/lib/install.sh
