theme = "catppuccin-mocha"
mode = "auto"
vcs = "git"
watch = false
exclude_untracked = false
line_numbers = true
tab_width = 4
file_gap = 1
hunk_gap = 0
wrap_lines = false
hunk_headers = true
menu_bar = true
animations = true
sidebar = "auto"
agent_notes = false
transparent_background = false
