require("telescope").load_extension('harpoon')

vim.keymap.set('n', '<leader>a', function()
  require("harpoon.mark").add_file()
end, { silent = true })
vim.keymap.set('n', '<C-e>', require("harpoon.ui").toggle_quick_menu, { silent = true })
vim.keymap.set('n', '<leader>sm', require('telescope').extensions.harpoon.marks, { desc = '[S]earch [M]arks' })

vim.keymap.set('n', '<leader>1', function()
    require("harpoon.ui").nav_file(1)
end, { silent = true })
vim.keymap.set('n', '<leader>2', function()
    require("harpoon.ui").nav_file(2)
end, { silent = true })
vim.keymap.set('n', '<leader>3', function()
    require("harpoon.ui").nav_file(3)
end, { silent = true })
vim.keymap.set('n', '<leader>4', function()
    require("harpoon.ui").nav_file(4)
end, { silent = true })
vim.keymap.set('n', '<leader>5', function()
    require("harpoon.ui").nav_file(5)
end, { silent = true })

