#!/usr/bin/env bash
#
# bootstrap installs things.

source ~/.dotfiles/scripts/utils.sh

backup_dir="~/.dotfiles/backups/$(date "+%Y_%m_%d-%H_%M_%S")/"
backup=

echo ''

# set ZSH as default shell
if [ -z "$ZSH_VERSION" ]; then
    _running "Setting default shell to ZSH"
    echo ''

    chsh -s $(grep /zsh$ /etc/shells | tail -1)
    echo ''

    _success "Default shell set to ZSH"
fi

# install dotfiles

# setup git
if ! [ -f git/gitconfig.symlink ]; then
    _running 'Setting up gitconfig'
    echo ''

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]; then
      git_credential='osxkeychain'
    fi

    read -p 'Author Name: ' git_authorname
    read -p 'Author E-Mail: ' git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" ~/.dotfiles/git/gitconfig.symlink.example > ~/.dotfiles/git/gitconfig.symlink

    echo ''
    _success 'gitconfig created'
fi

# install dotfiles
_running 'Installing dotfiles'

find -H "$HOME/.dotfiles" -maxdepth 2 -iname "*.symlink" | while read src; do
    dst="$HOME/.$(basename "${src%.*}")"
    if [ -e "$dst" ]; then
        _info "Backing up $dst"
        backup=1

        [[ -e "$backup_dir" ]] || mkdir -p "$backup_dir"
        mv "$dst" "$backup_dir"
    fi
    ln -s "$src" "$dst"
    _success "Linked $src to $dst"
done

_success 'dotfiles installed'
if [[ "$backup" ]]; then
    _info "\nBackups were moved to ~/${backup_dir#$HOME/}"
fi

echo ''
echo 'Finished!'
