#!/usr/bin/env bash
#
# Run all dotfiles installers.

source ~/.dotfiles/scripts/utils.sh

echo ''

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

echo ''
echo 'Dependencies installed successfully!'
