#!/usr/bin/env bash
#
# Updates things.

source scripts/utils.sh

echo ''

if [ $(which brew) ]; then
    _running "Updating Homebrew"
    echo ''

    brew update
    echo ''

    _success "Homebrew updated"

    _running "Upgrading formulaes"
    echo ''

    brew upgrade --all

    echo ''
    _success "Formulaes upgraded"
fi

echo ''
echo 'Updates completed!'
