#!/usr/bin/env bash
#
# Upgrade dotfiles by pulling git changes.

source scripts/utils.sh

echo ''
_running "Upgrading dotfiles"
echo ''

git checkout master
git pull origin master
echo ''

_success "dotfiles upgraded"
echo ''
echo 'Finished!'
